### ISSUE TITLE
Firebase v1 API

### ISSUE THREAD

**Issue by fraserbooth** [web-push-libs/web-push-csharp#107]
Now that Google have moved FCM over to the v1 API, will this library still work? If not, has anyone found an easy way to migrate for this to the new approach? Thanks, Fraser

**Comment by e-i-n-s** [comment]
Should be still supported when using with VAPID keys.

Source: `https://stackoverflow.com/questions/77957644/will-fcm-ditch-the-support-of-web-push-protocol`:
```
There are no currently plans to retire this endpoint for sending messages to Web Push tokens.
```

Other source: `https://groups.google.com/g/firebase-talk/c/3C2Vq9pIWr4?pli=1`

**Comment by fraserbooth** [comment]
Fantastic, thank you for those links, exactly what I was looking for.
