### ISSUE TITLE
System.AggregateException

### ISSUE THREAD

**Issue by adreu** [web-push-libs/web-push-csharp#15]
Hi,

I got this issue when I called
webPushClient.SendNotification(subscription, "payload", options);

I'm trying to migrate from php script Web Push to C#, so I check in php all keys, and it seems to work (using VAPID)

Do you have any ideas?

Exception levée : 'System.AggregateException' dans mscorlib.dll
done   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à WebPush.WebPushClient.SendNotification(PushSubscription subscription, String payload, Dictionary`2 options)

**Comment by adreu** [comment]
Ok after checks response of await httpClient.SendAsync(request) is :

response = {StatusCode: 400, ReasonPhrase: 'InvalidParameters', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:

And this is the request :
 System.Net.Http.ByteArrayContent, Headers:
{
  TTL: 2419200
  Encryption: salt=1jlqUA2jpFo7KQ_dMxeAIw
  Authorization: WebPush eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiJodHRwczovL2ZjbS5nb29nbGVhcGlzLmNvbSIsImV4cCI6MTUwMzEwMzAxMiwic3ViIjoibWFpbHRvOmV4YW1wbGVAZXhhbXBsZS5jb20ifQ.JlZRlYE5eqAJ2roRz4-UccbnFXO70wstI-7ymbgxvYx-6B34cvnXtqOvAv1p9HiawGrG4ZySXdT3hSFqUFojHw
  Crypto-Key: dh=BJU-Ox7bemC9Y1YInwSJc8WwujnrD67hIp0zwWHGNZy0DliLcHDO-8SYspGSV8LcOxW1tRFMwJUgxi2V-VF6fFs;p256ecdsa=BJGjyWr8QKSz3UeGczPbQaC8qrfizZ+ghxyOJogizfG6Z5simwivn7pJDxa+WnuqCa/ofwy1Wx5eIHVsSUvxXVE
  Content-Type: application/octet-stream
  Content-Length: 25
  Content-Encoding: aesgcm
}

**Comment by Vannevelj** [comment]
I just tried using this library and had the same issue.

**Comment by Vannevelj** [comment]
I'm not sure what the issue was but I tried it with VAPID keys (`VapidHelper.GenerateVapidKeys();`) and passed in the public key to 

```
registration.pushManager
   .subscribe({
                      userVisibleOnly: true,
                      applicationServerKey: urlBase64ToUint8Array("Public_Key")
   })
```

The base64 conversion function I found here: https://gist.github.com/malko/ff77f0af005f684c44639e4061fa8019

**Comment by adreu** [comment]
thanks for the help that war the issue !
