### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by mateusz2813** [web-push-libs/web-push-csharp#2]
Hi, 

i have a problem with firefox support. It's great working for chrome, but for firefox I received Unauthorize http status code.

I suppose it's a bug in c# library, because when I'm using the same keys with Node.js version (https://web-push-codelab.appspot.com/) all it's working fine.

Could you check this?

P.S. Thank you very much for this library! Good job!

**Comment by ericklombardo** [comment]
+1

**Comment by coryjthompson** [comment]
Thanks - I'll look into this in the next week.

**Comment by coryjthompson** [comment]
I've sent an update to NuGet (v1.0.7).
I'm now capable of receiving push notifications in Firefox. 
Let me know how you go.
Thanks again for your feedback.

**Comment by mateusz2813** [comment]
Thanks for your help, but unfortunately I'm receiving the same error on firefox - Unauthorized. :(

**Comment by coryjthompson** [comment]
I had an unusual caching issue when a built the project, which meant it was broken for build .NET 4.5. 

Please try updating to v1.0.8 and let me know.

**Comment by mateusz2813** [comment]
Yeah, it's working now! Thanks for your help!
