### ISSUE TITLE
Exception while passsing the payload parameter

### ISSUE THREAD

**Issue by binaamir** [web-push-libs/web-push-csharp#22]
Hi, I am able to send the the simple notification without the payload but when I pass the payload parameter an exception is thrown
`webPushClient.SendNotification(subscription, @"payload");`

the exception text is: **FormatException: Invalid point encoding 63**
Where I am doing wrong?

**Comment by coryjthompson** [comment]
Hi @binaamir,

Have you found any more information about this exception? I looked up the exception message and it's related to the ECCurve library. My guess would be invalid P256DH or Auth details.
