### ISSUE TITLE
Not working with Asp.Net Core 2

### ISSUE THREAD

**Issue by unsorted01** [web-push-libs/web-push-csharp#26]
I installed the 1.0.9 version from nugget in an asp.net core 2 project, but when i tried to send a push notification this exception happend:
TypeLoadException: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

**Comment by johnnyoshika** [comment]
I'm running into the same problem. :-(

**Comment by johnnyoshika** [comment]
The problem is probably related to this: https://github.com/dotnet/corefx/pull/18689

I installed the `System.Security.Cryptography.Cng` nuget package, but it didn't solve the problem.

**Comment by johnnyoshika** [comment]
The solution is to use this library instead: https://github.com/vip30/WebPush-NetCore

It's essentially a port of this one and the API is identical.

**Comment by coryjthompson** [comment]
1.0.10 is built to support asp.net core 2 and has just been released.
