### ISSUE TITLE
Support for full framework missing

### ISSUE THREAD

**Issue by nielsvoigt** [web-push-libs/web-push-csharp#32]
Hi Cory, 

RE: https://github.com/web-push-libs/web-push-csharp/pull/18

I don't know what happened, but the support for full frameworks is gone with the 1.0.10 version. I'm back to square one where your package wants to import a huge bunch of extra crap into my project, because it supports all kind of "Core" and "Standard" things, but completely overlooks that I might already have all that in my full framework (net45, net46 or net47) and don't need a second version installed.

Look at that:

![image](https://user-images.githubusercontent.com/26093284/36742316-a72837de-1be7-11e8-8d03-b90ad0af50ac.png)

I need your package and probably a full framework version of BouncyCastle. Nothing else. The rest will just put a bunch of incompatible stuff in my project.

Can you please bring back support for the full framework?

**Comment by coryjthompson** [comment]
Hi,

I've fixed the issue for 1.0.11. Thanks for bringing it to my attention. I'm still getting used to the new standard.

On a fresh 4.6.2 project:
![462](https://user-images.githubusercontent.com/561902/38122335-18c89492-3420-11e8-86a2-89a8584fcf43.PNG)

Thanks.

**Comment by ebonato** [comment]
After updating Nuget package to 1.0.11, its clear to see the lower # of dependencies.
After cleaning all the dependency mess from previous version, the nuget packager only installs dependencies from above screenshot.
But when using depency for a net462 project, WebPush throws an Exception when calling 
GenereteRequestDetails:
Exeption:
Não foi possível carregar arquivo ou assembly 'BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942' ou uma de suas dependências. O sistema não pode encontrar o arquivo especificado.
Stack Trace:
   em WebPush.Util.Encryptor.Encrypt(Byte[] userKey, Byte[] userSecret, Byte[] payload)
   em WebPush.Util.Encryptor.Encrypt(String userKey, String userSecret, String payload)
   em WebPush.WebPushClient.GenerateRequestDetails(PushSubscription subscription, String payload, Dictionary`2 options)
   in ......
Seems to be an error with Nuget Packaging/dependencies, not with code itselft
