### ISSUE TITLE
Getting a conversion exception

### ISSUE THREAD

**Issue by skartknet** [web-push-libs/web-push-csharp#39]
When sending notification I get: `The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.`

I can't figure what the input is, but i think it's one of the generated keys.

I have run all the Validate methods in the VapidHelper and everything goes fine.
```
private string _publicKey = @"BCvlec_uZKKZDzrf45jKLdAfLGBdKJZHjS7NsZt9GR-vW_iNF7mpbF-RKcq4nIbOeIkCYoDfG51njrtzFSTvT3E";
        private string _privateKey = @"oSj0DmpXB6shtz7bLHdk6EiiTtKIkhyR_QPIdtxIIrM";
        private string _subject = @"mailto:asdasd@gmail.com";

           var headers = GetVapidHeaders(notification.Endpoint);

            var subscription = new PushSubscription(notification.Endpoint, headers["Crypto-Key"], headers["Authorization"]);

            var options = new Dictionary<string, object>();
            options["vapidDetails"] = new VapidDetails(_subject, _publicKey, _privateKey);

                var webPushClient = new WebPushClient();
                webPushClient.SendNotification(subscription, "asd", options);
```

UPDATE
The conversion error is being thrown in Encryptor.cs:20 when trying to convert the keys. At this point the values I have are:

userKey: "p256ecdsa=BCvlec_uZKKZDzrf45jKLdAfLGBdKJZHjS7NsZt9GR-vW_iNF7mpbF-RKcq4nIbOeIkCYoDfG51njrtzFSTvT3E"

userSecret: "WebPush eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiJodHRwczovL2ZjbS5nb29nbGVhcGlzLmNvbSIsImV4cCI6MTUyMzgwMTkyMSwic3ViIjoibWFpbHRvOmFzZGFzZEBnbWFpbC5jb20ifQ.gKkX9HnaFtm_D2nMK0xpmw4Hwu5L5xdhasSvTS4HHuDWXo4FM73ii6WQvYTb2VYYqnAEAgLUnfxWJWqukiMTuQ"

**Comment by skartknet** [comment]
The issue was just inexperience :(

**Comment by skartknet** [comment]
I don't have that project anymore. For what I can see on what I posted in here, I'm passing an 'options' dictionary with the "vapidDetails" key to the SendNotification method. You have to pass the returned value from VapidDetails instead. Can you paste your code here?

**Comment by adam-therapynotes** [comment]
Thanks - I was finally able to solve it.  I had some confusion between the p256dh key returned from the user subscription, and the crypto-key header returned from GetVapidHeaders(), and had them swapped.  Just a case of me still learning the usage of everything in this spec.
