### ISSUE TITLE
Cannot send notification with expiration date

### ISSUE THREAD

**Issue by marcin-synak** [web-push-libs/web-push-csharp#41]
"WebPushClient.SendNotification" does not allow sending notification with expiration date.

Internally, it calls "VapidHelper.GetVapidHeaders" which has "expiration" parameter, but it is omitted and it defaults to 12 hours.

It would be nice if we could pass our own value somehow (perhaps through "VapidDetails" object?)

Or maybe there's a way to work around it which I did not find?
I'd be grateful for any help.

**Comment by coryjthompson** [comment]
You are correct - it's hard coded to 12 hours. I will add an option shortly. 

Thank you.

**Comment by coryjthompson** [comment]
VapidDetails.Expiration will exist in next nuget release.

Thank you.

**Comment by marcin-synak** [comment]
Splendid! We'll be waiting for the package update.

**Comment by marcin-synak** [comment]
Hello, is there a chance new NuGet package will appear soon? The last version is from March, 2018, I hope you did not abandon this project completely :)

Best regards.

**Comment by coryjthompson** [comment]
Hi, 

I'll publish a new version shortly.
