### ISSUE TITLE
Edge 17

### ISSUE THREAD

**Issue by miksh7** [web-push-libs/web-push-csharp#42]
Would Edge 17 support it? If yes, please update "Browser support".

**Comment by maheshbale-wingify** [comment]
Yeah, I would also like to know about the Edge 17

**Comment by erionalite** [comment]
Does this package work with Edge?

**Comment by erionalite** [comment]
Do we know if there is an extension path to making this working for Edge?

**Comment by coryjthompson** [comment]
Microsoft Edge is supported.

@tuwrraphael has mentioned: 
I tested this package successfully together with Edge.
Version
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

I'll update the readme.

thanks.
