### ISSUE TITLE
Indicating timeout for push request

### ISSUE THREAD

**Issue by zahyvolf** [web-push-libs/web-push-csharp#45]
Is there a plan to add timeout for the the HttpClient?  i've noticed the WebPushClient constructor can receive an HttpClientHandler, unfortunately the timeout argument belong to the HttpClient itself which is private/protected.

(The motivation is of course to prevent hangs during SendNotification.  I would use the Async method but that would mask the real send failures)

**Comment by tuwrraphael** [comment]
At the moment you could use the **GenerateRequestDetails** method of WebPushClient, and use your own HttpClient instance.
```C#
var httpClient = new HttpClient();
// set your options
var request = webPushClient.GenerateRequestDetails(...);
// override request parameters
await httpClient.SendAsync(request);
```

**Comment by coryjthompson** [comment]
A timeout would definitely be helpful. I'll look into it 👍

**Comment by coryjthompson** [comment]
WebPushClient now has an option to specify your own httpclient in which you can set your own timeout value.
`
var httpClient = new HttpClient();
httpClient.Timeout = TimeSpan.FromSeconds(100);
var webPush = new WebPushClient(httpClient);
`
