### ISSUE TITLE
Q: Can I use parallel foreach when calling webPushClient.SendNotification?

### ISSUE THREAD

**Issue by OmriY** [web-push-libs/web-push-csharp#47]
Hi,
I have a large amount of subscribers, and sending in regular foreach is taking too long,
I want to use parallel foreach when calling:
"SendNotification(PushSubscription subscription, string payload, VapidDetails vapidDetails)"
Will the pushServer can handle it ?

**Comment by tuwrraphael** [comment]
As the browser manufactorers' push servers are subjected to concurrent requests from different users all the time, I suspect it won't be a problem.
Be aware that, at the moment, an WebPushClient instance uses one HttpClient to send the request; I don't know if concurrent requests are supported by one HttpClient instance. Generating the HttpRequestMessages concurrently should not be a problem.

Keep in mind that web push notifications should be
> Timely, Relevant, and Precise (https://developers.google.com/web/fundamentals/push-notifications/)

And therefore also broadcast functionality is not part of the specification.

**Comment by trntsmn** [comment]
I'm in the same boat, wondering if there is any consensus on the best way to send a mass push message.

**Comment by OmriY** [comment]
**Update**: I am using parallel foreach when calling webPushClient.SendNotification and it seems it works fine.
