### ISSUE TITLE
Feature Request: Allow HttpClient to be provided for WebPushClient 

### ISSUE THREAD

**Issue by JaronrH** [web-push-libs/web-push-csharp#53]
Feature Request: would you consider changing WebPushClient so that the HttpClient could be provided either through the existing property or as a constructor argument?  I would like to be able to provide my own HttpClient through DI as that would allow me to take advantage of other technologies (Ex: Polly) through DI.  Thanks!

**Comment by hermanho** [comment]
When will be published to NuGet ? Is there any private feed to include this feature now?

**Comment by RouR** [comment]
Same question. Why this updates is not published to NuGet?
