### ISSUE TITLE
web-push-csharp latest not available in npm

### ISSUE THREAD

**Issue by kalaiarasubosch** [web-push-libs/web-push-csharp#68]
Team,

I noticed that web push csharp library is not updated in the nuget package manager.The library was last updated on March 30, 2018 (3/30/2018), but latest commit for same library was done on  Mar 16, 2019 for "Allow Vapid header to include expiration" changes. We have necessity to depend on the "Allow Vapid header to include expiration" changes, so It will be great if publish the latest WebPush library in nuget soon.

.

**Comment by jcmcbeth** [comment]
I too am waiting on an unreleased change.

**Comment by coryjthompson** [comment]
Hi,

Sorry for the delay. I've uploaded a new build of the library and it should be available within the hour. (v1.0.12)
