### ISSUE TITLE
Can't set cancellationToken

### ISSUE THREAD

**Issue by waleed1ace** [web-push-libs/web-push-csharp#77]
The current latest nuget version doesn't have the following method available:
public async Task SendNotificationAsync(PushSubscription subscription, string payload = null,
            Dictionary<string, object> options = null, CancellationToken cancellationToken=default)

But it's shown on the main readme page:
https://github.com/web-push-libs/web-push-csharp#sendnotificationasyncpushsubscription-payload-vapiddetailsgcmapikeyoptions-cancellationtoken

**Comment by coryjthompson** [comment]
Thanks, 

The newest version has been uploaded to nuget with the CancellationToken. (v1.0.12)
