### ISSUE TITLE
WebPushClient: Implement an interface for mocking in UnitTests

### ISSUE THREAD

**Issue by kristof12345** [web-push-libs/web-push-csharp#79]
Hi!

When trying to make unit tests for my app it'd be really useful to mock WebPushClient. For this creating an abstract base class or an interface would be really useful (or just making SendNotificationAsync overridable).

Thank you!

**Comment by coryjthompson** [comment]
Thanks for your advice.

IWebPushClient was introduced for mocking and released in v1.0.12
