### ISSUE TITLE
Expose a SendNotificationAsync Method

### ISSUE THREAD

**Issue by nikmd23** [web-push-libs/web-push-csharp#8]
It'd be great if we could send notifications asynchronously. 

It looks like there's an explicit `.Wait()` call right now.

**Comment by coryjthompson** [comment]
Agreed. I'll try and find some time this week to learn how to do ASYNC correctly pre .NET v4.5. 

I believe Microsoft.Bcl.Async is my way forwards while maintaining backwards compatibility and mono support.

**Comment by nikmd23** [comment]
Awesome!

I didn't think about pre .NET 4.5 support. I just assumed that there'd be an additional `async` method added for newer versions of .NET, but what you're thinking about could be promising. I'm looking forward to it.

**Comment by marsimoto03** [comment]
Hi,
any updates when this feature will be available and published as new version on nuget?
Thank you!

**Comment by coryjthompson** [comment]
Hi,

Sorry work ramped up quite a bit. I'm hoping to find some time this weekend. 

Once this feature is closed I will release on NuGet.

:)
