### ISSUE TITLE
Remove Newtonsoft.Json dependency

### ISSUE THREAD

**Issue by 7702244** [web-push-libs/web-push-csharp#84]
You are only using json serialization in the JwsSigner.cs class. Why not get rid of the heavy dependency Newtonsoft.Json and use the standard fast and simple JsonSerializer ([Documentation](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-5-0#how-to-write-net-objects-as-json-serialize))

**Comment by 7702244** [comment]
The project is abandoned?
Please, review the pull request #95

**Comment by au5ton** [comment]
JsonSerializer seems to only available in .NET Core 3.0 and later. This project seems to be targeting .NET versions before that, so Newtonsoft is necessary.

https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer?view=net-8.0#applies-to

**Comment by 7702244** [comment]
Maybe it would be better to make a separate version for the new .NET without unnecessary dependencies?

**Comment by coryjthompson** [comment]
Thanks @7702244. 

This has been merged and will be in the next release.
