### ISSUE TITLE
.NETStandard 2.0 not supported

### ISSUE THREAD

**Issue by idoshin4** [web-push-libs/web-push-csharp#87]
After I delete Visual studio 2019, when the trial has been over, There is no option to download .NETstandard anymore from the network so the project can't be built anymore due to the dependencies.
Please provide a solution for this.

**Comment by coryjthompson** [comment]
You should be able to simply install a .NET SDK for a version compatible with .NET standard 2.0

https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0
